#!/bin/bash
# Deployment script for yolov8l
# Generated by Wildfire Watch Model Converter

set -e

echo "Deploying yolov8l to Frigate..."

# Model files
MODEL_DIR="converted_models/640x640"
FRIGATE_MODEL_DIR="/opt/frigate/models"

# Copy models based on available hardware

if [ -f "$MODEL_DIR/yolov8l_hailo8.hef" ]; then
    echo "Copying Hailo model..."
    cp "$MODEL_DIR/yolov8l_hailo8.hef" "$FRIGATE_MODEL_DIR/"
fi

if [ -f "$MODEL_DIR/yolov8l_edgetpu.tflite" ]; then
    echo "Copying Edge TPU model..."
    cp "$MODEL_DIR/yolov8l_edgetpu.tflite" "$FRIGATE_MODEL_DIR/"
fi

if [ -f "$MODEL_DIR/yolov8l_cpu.tflite" ]; then
    echo "Copying CPU model..."
    cp "$MODEL_DIR/yolov8l_cpu.tflite" "$FRIGATE_MODEL_DIR/"
fi

# Copy labels
cp "$MODEL_DIR/yolov8l_labels.txt" "$FRIGATE_MODEL_DIR/"

# Copy Frigate config
cp "$MODEL_DIR/yolov8l_frigate_config.yml" "/opt/frigate/config/"

echo "Deployment complete!"
echo "Restart Frigate to use the new model."
