version: '3.8'

# Single file with profiles for different deployments
# Usage: docker-compose --profile production up

services:
  mqtt_broker:
    build: ./mqtt_broker
    container_name: mqtt-broker
    hostname: mqtt-broker
    restart: unless-stopped
    ports:
      - "${MQTT_PORT:-1883}:1883"
      - "${MQTT_TLS_PORT:-8883}:8883"
    volumes:
      - mqtt_data:/mosquitto/data
      - certs:/mnt/data/certs:ro
    networks:
      wildfire_net:
        ipv4_address: ${MQTT_STATIC_IP:-192.168.100.10}

  camera_detector:
    build: ./camera_detector
    container_name: camera-detector
    hostname: camera-detector
    restart: unless-stopped
    depends_on:
      - mqtt_broker
    environment:
      - MQTT_BROKER=${MQTT_BROKER:-mqtt-broker}
      - CAMERA_CREDENTIALS=${CAMERA_CREDENTIALS:-admin:,admin:admin}
    networks:
      - wildfire_net
    profiles:
      - production
      - development

  security_nvr:
    build: ./security_nvr
    container_name: security-nvr
    hostname: security-nvr
    restart: unless-stopped
    privileged: true
    depends_on:
      - mqtt_broker
      - camera_detector
    ports:
      - "5000:5000"
      - "8554:8554"
    volumes:
      - frigate_data:/media/frigate
      - certs:/mnt/data/certs:ro
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - FRIGATE_DETECTOR=${FRIGATE_DETECTOR:-auto}
    networks:
      - wildfire_net
    profiles:
      - production

  fire_consensus:
    build: ./fire_consensus
    container_name: fire-consensus
    hostname: fire-consensus
    restart: unless-stopped
    depends_on:
      - mqtt_broker
    environment:
      - MQTT_BROKER=${MQTT_BROKER:-mqtt-broker}
      - CONSENSUS_THRESHOLD=${CONSENSUS_THRESHOLD:-2}
    networks:
      - wildfire_net
    profiles:
      - production
      - development

  gpio_trigger:
    build: ./gpio_trigger
    container_name: gpio-trigger
    hostname: gpio-trigger
    restart: unless-stopped
    privileged: true
    depends_on:
      - mqtt_broker
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - MQTT_BROKER=${MQTT_BROKER:-mqtt-broker}
      - MAX_ENGINE_RUNTIME=${MAX_ENGINE_RUNTIME:-1800}
    networks:
      - wildfire_net
    profiles:
      - production
      - raspberry-pi

volumes:
  mqtt_data:
  frigate_data:
  certs:

networks:
  wildfire_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-192.168.100.0/24}
