#!/bin/bash
# YOLO-NAS Complete Pipeline Deployment Script
# Generated by fixed complete pipeline

set -e

echo "YOLO-NAS Wildfire Detection Deployment"
echo "====================================="
echo "Model: yolo_nas_s_wildfire_complete.onnx"
echo "Size: 51.5 MB"
echo "Classes: 32 (Fire at class 26)"
echo ""

# Check if Frigate directory is provided
if [ -z "$1" ]; then
    echo "Usage: $0 /path/to/frigate/directory"
    echo "Example: $0 /opt/frigate"
    echo "Example: $0 ./security_nvr"
    exit 1
fi

FRIGATE_DIR="$1"
MODELS_DIR="$FRIGATE_DIR/models"

# Create models directory if it doesn't exist
echo "Creating models directory..."
mkdir -p "$MODELS_DIR"

# Copy ONNX model
echo "Copying YOLO-NAS model..."
cp "../output/yolo_nas_s_wildfire_complete.onnx" "$MODELS_DIR/"

if [ $? -eq 0 ]; then
    echo "✓ Model deployed successfully"
else
    echo "✗ Model deployment failed"
    exit 1
fi

echo ""
echo "Deployment complete!"
echo ""
echo "Next steps:"
echo "1. Add the configuration from ../output/frigate_yolo_nas_complete_config.yml to your Frigate config.yml"
echo "2. Restart Frigate: docker-compose restart security_nvr"
echo "3. Monitor for fire detection events (class 26)"
echo ""
echo "Test the model:"
echo "- Check Frigate UI at http://your-server:5000"
echo "- Look for 'fire' detections in the Events tab"
echo "- Adjust thresholds in config if needed"
