#!/bin/bash
# Deployment script for yolov8n_demo
# Generated by Wildfire Watch Model Converter

set -e

echo "Deploying yolov8n_demo to Frigate..."

# Model files
MODEL_DIR="demo_output/416x416"
FRIGATE_MODEL_DIR="/opt/frigate/models"

# Copy models based on available hardware

if [ -f "$MODEL_DIR/yolov8n_demo_edgetpu.tflite" ]; then
    echo "Copying Edge TPU model..."
    cp "$MODEL_DIR/yolov8n_demo_edgetpu.tflite" "$FRIGATE_MODEL_DIR/"
fi

if [ -f "$MODEL_DIR/yolov8n_demo_cpu.tflite" ]; then
    echo "Copying CPU model..."
    cp "$MODEL_DIR/yolov8n_demo_cpu.tflite" "$FRIGATE_MODEL_DIR/"
fi

# Copy labels
cp "$MODEL_DIR/yolov8n_demo_labels.txt" "$FRIGATE_MODEL_DIR/"

# Copy Frigate config
cp "$MODEL_DIR/yolov8n_demo_frigate_config.yml" "/opt/frigate/config/"

echo "Deployment complete!"
echo "Restart Frigate to use the new model."
