#!/bin/bash
# Deployment script for yolo8l_fire_int8
# Generated by Wildfire Watch Model Converter

set -e

echo "Deploying yolo8l_fire_int8 to Frigate..."

# Model files
MODEL_DIR="output_int8/640x640"
FRIGATE_MODEL_DIR="/opt/frigate/models"

# Copy models based on available hardware

if [ -f "$MODEL_DIR/yolo8l_fire_int8_edgetpu.tflite" ]; then
    echo "Copying Edge TPU model..."
    cp "$MODEL_DIR/yolo8l_fire_int8_edgetpu.tflite" "$FRIGATE_MODEL_DIR/"
fi

if [ -f "$MODEL_DIR/yolo8l_fire_int8_cpu.tflite" ]; then
    echo "Copying CPU model..."
    cp "$MODEL_DIR/yolo8l_fire_int8_cpu.tflite" "$FRIGATE_MODEL_DIR/"
fi

# Copy labels
cp "$MODEL_DIR/yolo8l_fire_int8_labels.txt" "$FRIGATE_MODEL_DIR/"

# Copy Frigate config
cp "$MODEL_DIR/yolo8l_fire_int8_frigate_config.yml" "/opt/frigate/config/"

echo "Deployment complete!"
echo "Restart Frigate to use the new model."
